language: python
python:
- "2.7"
notifications:
  email:
    recipients:
      - patricia_j_h@hotmail.com
      - patriciajh1991@gmail.com
    on_success: [always|never|change] # default: always
    on_failure: [always|never|change] # default: always
    
# command to install dependencies
install:
- pip install pytest pytest-cov
- pip install radon
- pip install pep8
- pip install mockito

# command to run tests
script:
- py.test --cov . --cov-report term-missing